### ISSUE TITLE
module not found errors: '__main__' is not a package

### ISSUE THREAD

**Issue by kobi2187** [metacraft-labs/python-deduckt#4]
I just started using this tool, so maybe I'm doing something wrong.
I downloaded the chardet python library, and try to run py2nim on its python files.

```
kobi7@sumak:~/apps/py2nim$ ./py2nim /home/kobi7/apps/chardet-master/chardet/big5prober.py 
Traceback (most recent call last):
  File "/home/kobi7/apps/py2nim/python-deduckt/deduckt/deduckt.py", line 44, in main
    exec(mainpycode, globals, locals)
  File "/home/kobi7/apps/chardet-master/chardet/big5prober.py", line 28, in <module>
    from .mbcharsetprober import MultiByteCharSetProber
ModuleNotFoundError: No module named '__main__.mbcharsetprober'; '__main__' is not a package
python-deduckt problem
```

Can you verify by following these steps?
Thanks!

**Comment by kobi2187** [comment]
Python 2.7.13
Python 3.7.2
(if it matters)

**Comment by kobi2187** [comment]
hmm, it may be a problem with my local installation. does it work for you?
